version: '3'

services:

    nginx:
      image: "nginx"
      volumes:
        - ./default.conf:/etc/nginx/conf.d/default.conf
        - ./ssl:/etc/nginx/ssl
      ports:
        - 80:80
        - 443:443
      depends_on:
        - snappass    

    snappass:
      build: .
      image: rubik-ai/snappass
      ports:
        - "5000:5000"
      stop_signal: SIGINT
      environment:
        - REDIS_HOST=redis
        # - NO_SSL=True
      depends_on:
        - redis

    redis:
      image: "redis:latest"
